spring:
  datasource:
    url: jdbc:h2:mem:devDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  database-platform: org.hibernate.dialect.H2Dialect

debug: true
logging:
  level:
    root: DEBUG