spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    output:
      ansi:
        enabled: always
    hibernate:
      ddl-auto: update
  profiles:
    active: development

logging:
  level:
    root: WARN

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem